spring:
  application:
    name: ebanky
  datasource:
    url: jdbc:postgresql://localhost:5433/ebanky
    username: abdo
    password: abdo654321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/app-changelog.xml
    default-schema: liquibase_db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/abdellatif
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: ebanky-rest-api
      principle-attribute: preferred_username



